FROM bellsoft/liberica-openjdk-alpine:23-cds
LABEL authors="dilansachi"
COPY build/libs/ex409-broadcaster-app-1.0-SNAPSHOT.jar ./

ENTRYPOINT ["java", "-jar", "./ex409-broadcaster-app-1.0-SNAPSHOT.jar"]
