FROM bellsoft/liberica-openjdk-alpine:23-cds
LABEL authors="dilansachi"
COPY build/libs/ex113-image-application-1.0-SNAPSHOT.jar ./

ENTRYPOINT ["java", "-jar", "./ex113-image-application-1.0-SNAPSHOT.jar"]
