FROM bellsoft/liberica-openjdk-alpine:23-cds
LABEL authors="dilansachi"
COPY build/libs/ex304-ping-pong-application-1.0-SNAPSHOT.jar ./

ENTRYPOINT ["java", "-jar", "./ex304-ping-pong-application-1.0-SNAPSHOT.jar"]
